export const CASES = [
  ['CP-01', 'RF-01', 'Login, acceso protegido, logout y revocacion; registro/verificacion requiere bandeja de prueba.', 'Login y perfil 200; logout invalida JWT. Registro/verificacion solo se marca PASS con evidencia real de correo.'],
  ['CP-02', 'Seguridad', 'Acceso a una operación protegida sin autenticación.', 'HTTP 401 ante ausencia o invalidez de autenticación.'],
  ['CP-03', 'Seguridad', 'Operación administrativa solicitada por un rol sin autorización.', 'HTTP 403 para un usuario autenticado con rol insuficiente.'],
  ['CP-04', 'RF-03', 'Creación de evento propio por ORGANIZADOR aprobado.', 'El backend valida los datos y crea el evento correctamente.'],
  ['CP-05', 'RF-04', 'Publicación de evento EN_REVISION por ADMINISTRADOR.', 'El backend transiciona a PUBLICADO y el evento es visible en la consulta pública.'],
  ['CP-06', 'RF-06', 'Inscripción de USUARIO a evento gratuito y pagado.', 'Gratuito: CONFIRMADA sin Pago. Pagado: PENDIENTE_PAGO y monto oficial del backend.'],
  ['CP-07', 'Seguridad', 'Segunda inscripción del mismo participante al mismo evento.', 'El sistema impide la duplicación de la inscripción.'],
  ['CP-08', 'RF-07', 'Carga de comprobante privado válido de pago propio.', 'Archivo persistido y pago/inscripción PENDIENTE_VALIDACION; consulta propia devuelve el mismo pago.'],
  ['CP-09', 'Seguridad', 'Validación de pago por Administrador u Organizador autorizado.', 'El sistema actualiza el estado de pago según la decisión registrada.'],
  ['CP-10', 'RF-08', 'Generación de QR temporal de una sesión propia.', 'Token temporal asociado a sesión, con vigencia validada por backend.'],
  ['CP-11', 'RF-08', 'Asistencia móvil con QR vigente y GPS admisible.', 'Una asistencia por inscripción y sesión. Requiere evidencia de dispositivo.'],
  ['CP-12', 'RF-09', 'Generación de certificado de inscripción elegible.', 'El sistema genera el certificado y asigna código único de verificación.'],
  ['CP-13', 'RF-13', 'Verificación pública de certificado mediante código.', 'El endpoint público devuelve la información correspondiente; código no registrado se distingue de error de servidor.'],
  ['CP-14', 'Integración móvil', 'Consulta de eventos desde la aplicación Flutter.', 'La aplicación obtiene datos de API y muestra eventos disponibles.'],
  ['CP-15', 'Integración web', 'Consulta de operación administrativa desde Angular.', 'La aplicación web consume API y presenta información al usuario autorizado.'],
  ['CP-16', 'RF-01', 'Credenciales inválidas, token inválido o sesión revocada.', 'Rechazo según contrato (400 o 401); no se crea sesión válida indebida.'],
  ['CP-17', 'RF-03 / Seguridad', 'Datos inválidos, recurso ajeno o archivo de tipo/tamaño incorrecto.', 'La operación se rechaza sin alterar el recurso anterior.'],
  ['CP-18', 'RF-04 / Seguridad', 'Publicar/rechazar con rol insuficiente o estado incompatible.', '403 o conflicto de estado según API; el evento no se publica indebidamente.'],
  ['CP-19', 'RF-05', 'Catálogo, detalle y filtros con coincidencias e información de pago.', 'Solo eventos públicos visibles; instrucciones y QR opcional corresponden al evento.'],
  ['CP-20', 'RF-05', 'Filtros sin resultados o detalle inexistente/no visible.', 'Lista vacía o 404 según operación; sin datos inventados.'],
  ['CP-21', 'RF-07 / Seguridad', 'Comprobante rechazado, reenvío permitido y acceso a pago ajeno.', 'Reenvío validado en estado permitido; recurso ajeno protegido.'],
  ['CP-22', 'RF-08 / Seguridad', 'QR vencido/rotado, GPS fuera de regla o asistencia duplicada.', 'Rechazo backend sin crear una nueva asistencia.'],
  ['CP-23', 'RF-09 / RF-13', 'Falta de elegibilidad y código desconocido.', 'Generación rechazada; verificación de código inexistente no produce error de servidor.'],
  ['CP-24', 'RNF-01', 'Operaciones principales con 20 usuarios concurrentes.', 'Al menos 95 % de solicitudes en 3 segundos o menos.'],
  ['CP-25', 'RNF-02', 'Matriz de endpoints y roles.', 'Autenticación ausente/inválida y roles insuficientes son rechazados según contratos.'],
  ['CP-26', 'RNF-03', 'Tareas principales con participantes de prueba.', 'Al menos 80 % completa tareas sin asistencia; requiere protocolo y resultados humanos.'],
  ['CP-27', 'RNF-04', 'Compatibilidad Chrome, Edge, Firefox y Android 12+.', 'Flujos correctos en versiones/dispositivos registrados.'],
  ['CP-28', 'RNF-05', 'Monitoreo de disponibilidad durante el período de prueba.', 'Disponibilidad mínima 95 %, excluyendo mantenimiento programado.'],
].map(([id, requirement, scenario, expected]) => ({ id, requirement, scenario, expected }));
